import 'dart:async';
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:sodium/sodium.dart';

/// Number of random bytes generated by each sodium probe sample.
const int sodiumProbeRandomByteLength = 32;

/// Maximum accepted P95 sodium initialization duration for short-lived isolates.
const Duration sodiumProbeShortLivedP95Limit = Duration(milliseconds: 100);

/// Non-sensitive metadata returned from one sodium background probe.
final class SodiumProbeSample {
  /// Creates a sodium probe sample.
  const SodiumProbeSample({
    required this.initializationDuration,
    required this.randomByteLength,
    required this.hasExpectedRandomByteLength,
  });

  /// Time spent initializing sodium in the background isolate.
  final Duration initializationDuration;

  /// Length of the random buffer, without exposing its contents.
  final int randomByteLength;

  /// Whether [randomByteLength] matches [sodiumProbeRandomByteLength].
  final bool hasExpectedRandomByteLength;
}

/// Aggregated non-sensitive results from sequential sodium probe samples.
final class SodiumProbeSummary {
  /// Creates a sodium probe summary.
  SodiumProbeSummary(List<SodiumProbeSample> samples)
    : samples = List.unmodifiable(samples),
      _sortedInitializationDurations = _sortedDurations(samples) {
    if (samples.isEmpty) {
      throw ArgumentError.value(samples, 'samples', 'must not be empty');
    }
  }

  /// The sequential samples that produced this summary.
  final List<SodiumProbeSample> samples;

  final List<Duration> _sortedInitializationDurations;

  /// Whether every sample produced the expected random-byte metadata.
  bool get allSamplesValid => samples.every(
    (SodiumProbeSample sample) => sample.hasExpectedRandomByteLength,
  );

  /// Fastest sodium initialization duration.
  Duration get minimum => _sortedInitializationDurations.first;

  /// P50 initialization duration, calculated with the nearest-rank method.
  Duration get p50 => _percentile(0.50);

  /// P95 initialization duration, calculated with the nearest-rank method.
  Duration get p95 => _percentile(0.95);

  /// Slowest sodium initialization duration.
  Duration get maximum => _sortedInitializationDurations.last;

  /// Whether short-lived isolates meet the spike's acceptance rule.
  bool get recommendsShortLivedIsolate =>
      allSamplesValid && p95 <= sodiumProbeShortLivedP95Limit;

  Duration _percentile(double percentile) {
    final int nearestRank = (percentile * _sortedInitializationDurations.length)
        .ceil();
    return _sortedInitializationDurations[nearestRank - 1];
  }

  static List<Duration> _sortedDurations(List<SodiumProbeSample> samples) {
    final List<Duration> durations =
        samples
            .map((SodiumProbeSample sample) => sample.initializationDuration)
            .toList()
          ..sort();
    return List.unmodifiable(durations);
  }
}

/// Captures the non-sensitive runtime context for an integration-test report.
final class SodiumProbeEnvironment {
  /// Creates an environment report.
  const SodiumProbeEnvironment({
    required this.operatingSystem,
    required this.operatingSystemVersion,
    required this.processorCount,
  });

  /// Runtime operating-system name.
  final String operatingSystem;

  /// Runtime operating-system version.
  final String operatingSystemVersion;

  /// Number of processors reported by the Dart runtime.
  final int processorCount;

  /// Serializes the environment without collecting user or vault data.
  Map<String, Object> toReportData() => <String, Object>{
    'operatingSystem': operatingSystem,
    'operatingSystemVersion': operatingSystemVersion,
    'processorCount': processorCount,
  };
}

/// Runs short-lived sodium initialization probes in background isolates.
abstract final class SodiumIsolateProbe {
  /// Runs one sample in a new isolate and returns non-sensitive metadata only.
  static Future<SodiumProbeSample> runSample() async {
    final Map<String, Object> report = await Isolate.run<Map<String, Object>>(
      _runSampleInBackground,
      debugName: 'sodium-isolate-probe',
    );
    return SodiumProbeSample(
      initializationDuration: Duration(
        microseconds: report['initializationMicroseconds']! as int,
      ),
      randomByteLength: report['randomByteLength']! as int,
      hasExpectedRandomByteLength:
          report['hasExpectedRandomByteLength']! as bool,
    );
  }

  /// Runs [sampleCount] samples one at a time and summarizes their timings.
  static Future<SodiumProbeSummary> runSequentialSamples({
    int sampleCount = 30,
  }) async {
    if (sampleCount <= 0) {
      throw ArgumentError.value(sampleCount, 'sampleCount', 'must be positive');
    }

    final List<SodiumProbeSample> samples = <SodiumProbeSample>[];
    for (var sampleIndex = 0; sampleIndex < sampleCount; sampleIndex++) {
      samples.add(await runSample());
    }
    return SodiumProbeSummary(samples);
  }

  /// Returns non-sensitive runtime information for integration-test reports.
  static SodiumProbeEnvironment captureEnvironment() => SodiumProbeEnvironment(
    operatingSystem: Platform.operatingSystem,
    operatingSystemVersion: Platform.operatingSystemVersion,
    processorCount: Platform.numberOfProcessors,
  );

  /// Verifies that an error raised in a background isolate reaches its caller.
  ///
  /// This exists only to exercise the isolate error-transport path in tests.
  static Future<void> throwInBackgroundForTesting() =>
      Isolate.run<void>(_throwProbeFailure, debugName: 'sodium-isolate-error');

  /// Clears [bytes] in place.
  ///
  /// The method is public solely so automated tests can verify the clearing
  /// primitive used by the probe's `finally` block. Callers must not log bytes.
  static void clearBytesForTesting(Uint8List bytes) {
    bytes.fillRange(0, bytes.length, 0);
  }
}

Future<Map<String, Object>> _runSampleInBackground() async {
  final Stopwatch stopwatch = Stopwatch()..start();
  final Sodium sodium = await SodiumInit.init();
  stopwatch.stop();

  Uint8List? randomBytes;
  try {
    randomBytes = sodium.randombytes.buf(sodiumProbeRandomByteLength);
    final int randomByteLength = randomBytes.length;
    return <String, Object>{
      'initializationMicroseconds': stopwatch.elapsedMicroseconds,
      'randomByteLength': randomByteLength,
      'hasExpectedRandomByteLength':
          randomByteLength == sodiumProbeRandomByteLength,
    };
  } finally {
    if (randomBytes != null) {
      SodiumIsolateProbe.clearBytesForTesting(randomBytes);
    }
  }
}

Never _throwProbeFailure() {
  throw StateError('intentional sodium isolate probe failure');
}
